// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKUmGrL7vS9PU7G30REMpSEZhnoT58xAk',
    appId: '1:639048545067:web:21b7cb02691f47fec80b6e',
    messagingSenderId: '639048545067',
    projectId: 'checklist-atm',
    authDomain: 'checklist-atm.firebaseapp.com',
    storageBucket: 'checklist-atm.appspot.com',
    measurementId: 'G-WV69D1Y158',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAph-uR6rivKtHRxYgvhxTXthDPvdQf3FI',
    appId: '1:639048545067:android:7c0cbb70df9dae3cc80b6e',
    messagingSenderId: '639048545067',
    projectId: 'checklist-atm',
    storageBucket: 'checklist-atm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvABUOsZUWCpU7fjcTCY89SGmGfFowm-s',
    appId: '1:639048545067:ios:8b6c3f6675825ef1c80b6e',
    messagingSenderId: '639048545067',
    projectId: 'checklist-atm',
    storageBucket: 'checklist-atm.appspot.com',
    iosClientId: '639048545067-vlij5c8oo96vun1sr5vjagdti1s5eqgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.checklistAtm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvABUOsZUWCpU7fjcTCY89SGmGfFowm-s',
    appId: '1:639048545067:ios:7570e788fe1b7678c80b6e',
    messagingSenderId: '639048545067',
    projectId: 'checklist-atm',
    storageBucket: 'checklist-atm.appspot.com',
    iosClientId: '639048545067-hsiiinheoeguirl6tmvlritj4koe1ktu.apps.googleusercontent.com',
    iosBundleId: 'com.example.telkom',
  );
}
